export enum Variant {
   ULTRA_BULLET = "ultraBullet",
   BULLET = "bullet",
   BLITZ = "blitz",
   RAPID = "rapid",
   CLASSICAL = "classical",
   CORRESPONDENCE = "correspondence",
   CHESS960 = "chess960",
   CRAZYHOUSE = "crazyhouse",
   ANTICHESS = "antichess",
   ATOMIC = "atomic",
   HORDE = "horde",
   KING_OF_THE_HILL = "kingOfTheHill",
   RACING_KINGS = "racingKings",
   THREE_CHECK = "threeCheck",
}
